version: '3'

services:

### MySQL ################################################
  mysql:
    build:
      context: ./mysql
      args:
        - MYSQL_VERSION=${MYSQL_VERSION}
    volumes:
      - ${RUNTIME_PATH}/data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"

### Nginx ################################################
  nginx:
    build:
      context: ./nginx
    ports:
        - "${NGINX_PORT}:80"
    volumes:
        - ${RUNTIME_PATH}/log/nginx:/var/log/nginx

### Node ################################################
  node:
    build: 
      context: ./node
      args:
        - NODE_VERSION=${NODE_VERSION}
        - NODE_REGISTRY=${NODE_REGISTRY}
    tty: true
    ports:
      - "${NODE_PORT}:3000"

### Php ################################################
  php:
    build:
      context: ./php
      args:
        - PHP_VERSION=${PHP_VERSION}
        - INSTALL_XDEBUG=${PHP_INSTALL_XDEBUG}
    volumes:
      - ${RUNTIME_PATH}/log/nginx/php:/var/log/nginx
      - ./php/sites:/etc/nginx/sites-available
      - ./php/xdebug.ini/:/usr/local/etc/php/conf.d/xdebug.ini
    ports:
      - "${PHP_NGINX_PORT}:80"

### Python ################################################
  python:
    build: 
      context: ./python
      args:
        - PYTHON_VERSION=${PYTHON_VERSION}
    tty: true

### Redis ################################################
  redis:
    build: ./redis
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ${RUNTIME_PATH}/data/redis:/data

### Redis ################################################
  golang:
    build:
      context: ./golang
      args:
        - GO_VERSION=${GO_VERSION}




